### ISSUE TITLE
fmt.Printf()

### ISSUE THREAD

**Issue by lrweck** [x1unix/go-playground#76] opened 2021-09-06 16:38 UTC
Hi!

Printing with fmt.Printf("%+v", myStruct) shows nothing on the console output.

fmt.Println() works fine

**Comment by x1unix** [comment] 2021-09-06 19:36
@lrweck hi. Are you using WASM runtime or the default one (specified in settings).

Can you share please a snippet?

**Comment by karanssh** [comment] 2021-11-27 20:09
https://goplay.tools/snippet/Z7mmkYc4Frj

I tried it now, but I was not able to reproduce it, it seems to show up fine for me on this simple snippet

**Comment by karanssh** [comment] 2022-03-14 11:11
@x1unix , re-verified on macOS mojave with google chrome - not able to repro this bug.

**Comment by x1unix** [comment] 2022-03-14 11:14
@karanssh thank you for a reply. Closing the ticket for now.

**Closed by x1unix** 2022-03-14 11:14 UTC
