### ISSUE TITLE
Support new go 1.18

### ISSUE THREAD

**Issue by vuon9** [x1unix/go-playground#135] opened 2022-03-18 10:26 UTC
Thanks for this wonderful Go Playground!

Could we also support go 1.18 as the default? It benefits in play with generics and other new features.
And still keep the old version as multiple choices (I assume many people still need it)?

**Comment by x1unix** [comment] 2022-03-18 12:19
Go 1.18 is supported out of the box. See #129 

Closing as duplicate of https://github.com/x1unix/go-playground/issues/105

**Closed by x1unix** 2022-03-18 12:19 UTC
